<?php

function _custom_producto_get_categoria() {
    $tid = false;
    $node = menu_get_object();
    if ($node && $node->type == 'productos') {
        $tid = $node->field_categor_a[LANGUAGE_NONE][0]['tid'];
    }
    return $tid;
}

function _custom_producto_block_show() {
    return true;
}

function _custom_producto_block_filter_show($type) {
    $is_visible = false;
    switch ($type) {
        case 'linea':
            if ((arg(0) == 'productos' && arg(2) == NULL) || (arg(0) == 'productos' && arg(2) == 'linea')) {
                $term_name = arg(1);
                $term = taxonomy_get_term_by_name($term_name, 'categor_a');
                $term = array_shift($term);
                if ($term->vid == 8) {
                    $is_visible = true;
                }
            }
            break;
    }
    return $is_visible;
}

function custom_producto_block_info() {
    $blocks['detail_product'] = array(
        'info' => t('Detalles de Producto'),
        'cache' => DRUPAL_CACHE_PER_PAGE,
        'visibility' => BLOCK_VISIBILITY_PHP,
        'pages' => '<?php return _custom_producto_block_show();?>',
    );
    $blocks['filter_linea'] = array(
        'info' => t('Filtro de producto por lineas'),
        'cache' => DRUPAL_CACHE_PER_PAGE,
        'visibility' => BLOCK_VISIBILITY_PHP,
        'pages' => '<?php return _custom_producto_block_filter_show("linea");?>',
    );
    $blocks['filter_all'] = array(
        'info' => t('Filtro de Categorias/Ambientes/Prop de Productos'),
        'cache' => DRUPAL_CACHE_PER_PAGE,
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => 'productos/*
producto/*',
    );
    return $blocks;
}

function custom_producto_block_view($delta = '') {
    $block = array();
    require_once drupal_get_path('module', 'custom_producto') . '/custom_producto.inc';
    require_once drupal_get_path('module', 'pathauto') . '/pathauto.inc';
    switch ($delta) {
        case 'detail_product':
            $node = node_load(arg(1));
            $block['subject'] = '';
            $block['content'] = array(
                '#theme' => 'custom_producto_detail',
                '#node' => $node,
            );
            break;
        case 'filter_linea':
            $arg = pathauto_cleanstring(arg(1));
            $items = _custom_producto_get_items_filtro_linea($arg);

            $list = array();
            foreach ($items as $item) {
                $name = pathauto_cleanstring($item->name);
                $list[] = l($item->name, "productos/$arg/linea/$name");
            }

            $block['content'] = array(
                '#theme' => 'custom_filter_linea',
                '#list' => theme('item_list', array('items' => $list, 'type' => 'ul',)),
                '#category' => $arg,
            );
            break;
        case 'filter_all':
            drupal_add_js(drupal_get_path('module', 'custom_producto') . '/js/custom_producto_menu.js');
            $term = _custom_producto_get_term_from_arg();
            if ($term) {
                $items = _custom_producto_get_items_filtro_all($term->name);
                $block['subject'] = $term->name;
                $block['content'] = array(
                    '#theme' => 'custom_filter_all',
                    '#list' => theme('item_list', array('items' => $items, 'type' => 'ul',)),
                );
            }
            break;
    }
    return $block;
}

function custom_producto_theme() {
    return array(
        'custom_producto_detail' => array(
            'template' => 'templates/custom_producto_detail',
            'variables' => array('node' => NULL,),
        ),
        'custom_filter_linea' => array(
            'template' => 'templates/custom_filter_linea',
            'variables' => array('list' => '', 'category' => '',),
        ),
        'custom_filter_all' => array(
            'template' => 'templates/custom_filter_all',
            'variables' => array('list' => '',),
        ),
    );
}
