<?php

/**
 * Implements hook_field_formatter_info().
 */
function custom_producto_flip_image_field_formatter_info() {
	return array (
			'custom_producto_flip_image' => array (
					'label' => t ( 'Image Flip' ),
					'field types' => array (
							'image' 
					) 
			) 
	);
}

/**
 * Implements hook_field_formatter_view().
 */
function custom_producto_flip_image_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
	$element = array ();
	drupal_add_css ( drupal_get_path ( 'module', 'custom_producto_flip_image' ) . '/css/fliper.css' );
	drupal_add_js ( drupal_get_path ( 'module', 'custom_producto_flip_image' ) . '/js/fliper.js' );
	foreach ( $items as $delta => $item ) {
		$element [$delta] = array (
				'#theme' => 'custom_producto_flip_image_image_formatter',
				'#item' => $item,
				'#entity_type' => $entity_type,
				'#entity' => $entity,
				'#node' => $entity, // Left for legacy support.
				'#field' => $field,
				'#display_settings' => $display ['settings'],
				'#delta' => $delta 
		);
	}
	
	return $element;
}

/**
 * Implements hook_theme().
 */
function custom_producto_flip_image_theme() {
	return array (
			'custom_producto_flip_image_image_formatter' => array (
					'variables' => array (
							'item' => NULL,
							'entity_type' => NULL,
							'entity' => NULL,
							'node' => NULL, // Left for legacy support.
							'field' => array (),
							'display_settings' => array (),
							'delta' => null 
					),
					'template' => 'template/custom-producto-flip-image-field' 
			) 
	);
}
